-- AlterTable
ALTER TABLE "Sale"
ADD COLUMN "pwdDiscount" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "pwdId" TEXT,
ADD COLUMN "vatExempt" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "vatAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Payment"
ADD COLUMN "pwdDiscount" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "pwdId" TEXT,
ADD COLUMN "vatExempt" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "vatAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
